apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 
  namespace: play
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: -app
    spec:
      containers:
        - name: 
          image: host.docker.internal:5000//:
          ports:
          - containerPort: 8080
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APP_NAME
              value: 
            - name: POD_INST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ENV_STAGE
              value: local
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: WKR_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WKR_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: LOGGING_LEVEL
              value: DEBUG
            - name: JAVA_OPTS
              value: -Dappdynamics.http.proxyHost= -Dappdynamics.http.proxyPort= -Dappdynamics.controller.hostName= -Dappdynamics.controller.port= -Dappdynamics.agent.accountName= -Dappdynamics.agent.accountAccessKey= -Dappdynamics.agent.applicationName= -Dappdynamics.agent.tierName= -Dappdynamics.agent.nodeName=-192.168.99.1-local -Dappdynamics.controller.ssl.enabled=true

# this uses the shared hsbc docker registry
