apiVersion: v1
kind: Service
metadata:
  name: platform-example-spring
  namespace: play
spec:
  selector:
    app: platform-example-spring-app
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    targetPort: 8080
