apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentdconf
  namespace: kube-system
data:
  fluent.conf: |
    <match fluent.**>
      @type null
    </match>
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>
    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>
    <match kubernetes.var.log.containers.**kube-system**.log>
      @type elasticsearch
      log_level info
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
      password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
      reload_connections "#{ENV['FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS'] || 'true'}"
      logstash_prefix "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX'] || 'logstash'}"
      logstash_format true
      buffer_chunk_limit 2M
      buffer_queue_limit 32
      flush_interval 5s
      max_retry_wait 30
      disable_retry_limit
      num_threads 8
    </match>
    <match kubernetes.var.log.containers.**platform**.log>
      @type remote_syslog
      host "#{ENV['SYSLOG_HOST']}"
      port "#{ENV['SYSLOG_PORT']}"
      severity debug
      program fluentd
      hostname ${tag[1]}
      <buffer tag>
      </buffer>
      <format>
        @type single_value
        message_key msg
      </format>
    </match>
    <match **>
      @type remote_syslog
      host "#{ENV['SYSLOG_HOST']}"
      port "#{ENV['SYSLOG_PORT']}"
      severity debug
      program fluentd
      hostname ${tag[1]}
      <buffer tag>
      </buffer>
      <format>
        @type single_value
        message_key msg
      </format>
    </match>
