apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana-logging-v2
  namespace: kube-system
  labels:
    k8s-app: kibana-logging
    version: v2
    #kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kibana-logging
    version: v2
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
        version: v2
        #kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kibana-logging
        image: kibana:4.6.6
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch-logging:9200"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
