version: "3.1"

services:
  dns:
    image: andyshinn/dnsmasq
    command: -d -A /local.service.platform/$MINIKUBE_IP -A /docker.for.mac.host.internal/$SHP_NODE_IP
    ports:
      - 53:53/tcp
      - 53:53/udp
    restart: unless-stopped
